name: C++

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: cd directory
        run: cd GameServer/cmake-build-debug
      - name: build
        run: cmake --build . --target GameServer -- -j 2
